CREATE TABLE ldap_searches (
	search_id		bigint				    NOT NULL,
	server_id		bigint				    NOT NULL,
	status			integer		DEFAULT 0	    NOT NULL,
	display_name		varchar(255)	DEFAULT ''	    NOT NULL,
	group_base_dn		varchar(255)	DEFAULT ''	    NOT NULL,
	group_filter		varchar(2048)	DEFAULT ''	    NOT NULL,
	group_scope		integer		DEFAULT 0	    NOT NULL,
	user_base_dn		varchar(255)	DEFAULT ''	    NOT NULL,
	user_filter		varchar(2048)	DEFAULT ''	    NOT NULL,
	user_scope		integer		DEFAULT 0	    NOT NULL,
	user_type_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	user_type_default	integer		DEFAULT 1	    NOT NULL,
	alias_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	name_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	surname_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	language_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	language_default	varchar(5)	DEFAULT ''	    NOT NULL,
	theme_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	theme_default		varchar(128)	DEFAULT 'default'   NOT NULL,
	autologin_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	autologin_default	integer		DEFAULT 0	    NOT NULL,
	autologout_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	autologout_default	integer		DEFAULT 900	    NOT NULL,
	refresh_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	refresh_default		integer		DEFAULT 30	    NOT NULL,
	rows_per_page_attr	varchar(255)	DEFAULT ''	    NOT NULL,
	rows_per_page_default	integer		DEFAULT 50	    NOT NULL,
	url_after_login_attr	varchar(255)	DEFAULT ''	    NOT NULL,
	url_after_login_default varchar(255)	DEFAULT ''	    NOT NULL,
	media_type_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	media_type_default	bigint				    NOT NULL,
	send_to_attr		varchar(255)	DEFAULT ''	    NOT NULL,
	send_to_default		varchar(100)	DEFAULT ''	    NOT NULL,
	when_active_attr	varchar(255)	DEFAULT ''	    NOT NULL,
	when_active_default	varchar(1024)	DEFAULT '1-7,00:00-24:00' NOT NULL,
	media_enabled_attr	varchar(255)	DEFAULT ''	    NOT NULL,
	media_enabled_default	integer		DEFAULT '0'	    NOT NULL,
	use_if_severity_attr	varchar(255)	DEFAULT ''	    NOT NULL,
	use_if_severity_default integer		DEFAULT '63'	    NOT NULL,
	PRIMARY KEY (search_id)
);
CREATE UNIQUE INDEX ldap_searches_1 ON ldap_searches (display_name);
ALTER TABLE ONLY ldap_searches ADD CONSTRAINT c_ldap_searches_1 FOREIGN KEY (server_id) REFERENCES ldap_servers (server_id);
